
#include "perf-timer-events.hpp"


std::vector<PerfEvent> get_all_events() {
    static std::vector<PerfEvent> ALL = {
        CPU_CLK_UNHALTED_ONE_THREAD_ACTIVE,
        CPU_CLK_UNHALTED_REF_TSC          ,
        CPU_CLK_UNHALTED_REF_XCLK         ,
        CPU_CLK_UNHALTED_REF_XCLK_ANY     ,
        CPU_CLK_UNHALTED_RING0_TRANS      ,
        CPU_CLK_UNHALTED_THREAD           ,
        CPU_CLK_UNHALTED_THREAD_ANY       ,
        CPU_CLK_UNHALTED_THREAD_P         ,
        CPU_CLK_UNHALTED_THREAD_P_ANY     ,
        CYCLE_ACTIVITY_CYCLES_L1D_MISS    ,
        CYCLE_ACTIVITY_STALLS_L1D_MISS    ,
        HW_INTERRUPTS_RECEIVED            ,
        INST_RETIRED_ANY                  ,
        INST_RETIRED_ANY_P                ,
        L1D_REPLACEMENT                   ,
        L1D_PEND_MISS_FB_FULL             ,
        L1D_PEND_MISS_PENDING             ,
        L1D_PEND_MISS_PENDING_CYCLES      ,
        L1D_PEND_MISS_PENDING_CYCLES_ANY  ,
        L2_RQSTS_ALL_CODE_RD              ,
        L2_RQSTS_ALL_DEMAND_DATA_RD       ,
        L2_RQSTS_ALL_DEMAND_MISS          ,
        L2_RQSTS_ALL_DEMAND_REFERENCES    ,
        L2_RQSTS_ALL_PF                   ,
        L2_RQSTS_ALL_RFO                  ,
        L2_RQSTS_CODE_RD_HIT              ,
        L2_RQSTS_CODE_RD_MISS             ,
        L2_RQSTS_DEMAND_DATA_RD_HIT       ,
        L2_RQSTS_DEMAND_DATA_RD_MISS      ,
        L2_RQSTS_MISS                     ,
        L2_RQSTS_PF_HIT                   ,
        L2_RQSTS_PF_MISS                  ,
        L2_RQSTS_REFERENCES               ,
        L2_RQSTS_RFO_HIT                  ,
        L2_RQSTS_RFO_MISS                 ,
        MEM_INST_RETIRED_ALL_LOADS        ,
        MEM_INST_RETIRED_ALL_STORES       ,
        MEM_INST_RETIRED_LOCK_LOADS       ,
        MEM_INST_RETIRED_SPLIT_LOADS      ,
        MEM_INST_RETIRED_SPLIT_STORES     ,
        MEM_INST_RETIRED_STLB_MISS_LOADS  ,
        MEM_INST_RETIRED_STLB_MISS_STORES ,
        MEM_LOAD_RETIRED_FB_HIT           ,
        MEM_LOAD_RETIRED_L1_HIT           ,
        MEM_LOAD_RETIRED_L1_MISS          ,
        MEM_LOAD_RETIRED_L2_HIT           ,
        MEM_LOAD_RETIRED_L2_MISS          ,
        MEM_LOAD_RETIRED_L3_HIT           ,
        MEM_LOAD_RETIRED_L3_MISS          ,
        UOPS_DISPATCHED_PORT_PORT_0       ,
        UOPS_DISPATCHED_PORT_PORT_1       ,
        UOPS_DISPATCHED_PORT_PORT_2       ,
        UOPS_DISPATCHED_PORT_PORT_3       ,
        UOPS_DISPATCHED_PORT_PORT_4       ,
        UOPS_DISPATCHED_PORT_PORT_5       ,
        UOPS_DISPATCHED_PORT_PORT_6       ,
        UOPS_DISPATCHED_PORT_PORT_7       ,
        UOPS_ISSUED_ANY                   ,

    };
    return ALL;
}